#!/usr/bin/env python3
import logging
import os

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "cpchain.market.market.settings")
django.setup()
from cpchain.market.product.models import Product
logger = logging.getLogger(__name__)


if __name__ == '__main__':
    logger.info('index product start')
    Product.bulk_indexing()
    logger.info('index product end')
