# Generated by Django 2.0.3 on 2018-05-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200, verbose_name='publicKey')),
                ('market_hash', models.CharField(max_length=256, verbose_name='market hash')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200, verbose_name='publicKey')),
                ('order_id', models.IntegerField(verbose_name='generate by chain')),
                ('market_hash', models.CharField(max_length=256, verbose_name='market_hash')),
                ('file_uuid', models.CharField(max_length=32, verbose_name='file_uuid')),
                ('file_title', models.CharField(max_length=256, verbose_name='file_title')),
                ('path', models.CharField(max_length=256, verbose_name='path')),
                ('size', models.IntegerField(verbose_name='size(byte)')),
                ('is_downloaded', models.BooleanField(verbose_name='True:downloaded,False:not downloaded')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='tag')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200, verbose_name='publicKey')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='name')),
                ('hashcode', models.CharField(max_length=200, null=True, verbose_name='hashcode')),
                ('path', models.CharField(max_length=200, null=True, verbose_name='path')),
                ('size', models.IntegerField(default=0, verbose_name='size')),
                ('remote_type', models.CharField(max_length=32, null=True, verbose_name='remote_type')),
                ('remote_uri', models.CharField(max_length=200, null=True, verbose_name='remote_uri')),
                ('is_published', models.BooleanField(verbose_name='True:published,False:unpublished')),
                ('aes_key', models.CharField(max_length=200, null=True, verbose_name='aes_key')),
                ('market_hash', models.CharField(max_length=256, null=True, verbose_name='market_hash')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoVersion',
            fields=[
                ('public_key', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='publicKey')),
                ('version', models.IntegerField(default=0, verbose_name='version')),
            ],
        ),
    ]
