# Generated by Django 2.0.3 on 2018-05-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfileinfo',
            name='client_id',
            field=models.IntegerField(default=0, verbose_name='client id'),
        ),
        migrations.AlterField(
            model_name='buyerfileinfo',
            name='order_id',
            field=models.IntegerField(null=True, verbose_name='generate by chain'),
        ),
    ]
