# Generated by Django 2.0.3 on 2018-05-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoVersion',
            fields=[
                ('public_key', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='PublicKey')),
                ('version', models.IntegerField(default=0, verbose_name='version')),
            ],
        ),
        migrations.AlterField(
            model_name='buyerfileinfo',
            name='file_title',
            field=models.CharField(max_length=256, verbose_name='file_title'),
        ),
    ]
