# Generated by Django 2.0.3 on 2018-05-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_auto_20180521_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfileinfo',
            name='aes_key',
            field=models.CharField(max_length=1024, null=True, verbose_name='aes_key'),
        ),
        migrations.AlterField(
            model_name='uploadfileinfo',
            name='name',
            field=models.CharField(max_length=256, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='uploadfileinfo',
            name='path',
            field=models.CharField(max_length=1024, null=True, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='uploadfileinfo',
            name='remote_uri',
            field=models.CharField(max_length=1024, null=True, verbose_name='remote_uri'),
        ),
    ]
