# Generated by Django 2.0.3 on 2018-05-07 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_auto_20180505_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerfileinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadfileinfo',
            name='public_key',
            field=models.CharField(max_length=200, verbose_name='publicKey'),
        ),
        migrations.AlterField(
            model_name='userinfoversion',
            name='public_key',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='publicKey'),
        ),
    ]
