# Generated by Django 2.0.3 on 2018-03-30 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180330_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 10, 16, 21, 547135), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='active_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 10, 16, 21, 547135), verbose_name='active date'),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 10, 16, 21, 547135), verbose_name='created date'),
        ),
    ]
