# Generated by Django 2.0.3 on 2018-03-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='walletuser',
            options={'ordering': ('created', 'public_key')},
        ),
        migrations.AddField(
            model_name='token',
            name='public_key',
            field=models.CharField(default=9999, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
