# Generated by Django 2.0.3 on 2018-03-30 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180330_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 2, 16, 59, 920809, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='active_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 2, 16, 59, 920809, tzinfo=utc), verbose_name='active date'),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 2, 16, 59, 920809, tzinfo=utc), verbose_name='created date'),
        ),
    ]
