# Generated by Django 2.0.3 on 2018-05-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
        migrations.AlterField(
            model_name='hottag',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1),
        ),
    ]
