# Generated by Django 2.0.3 on 2018-05-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hottag',
            name='name',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='index',
            field=models.IntegerField(default=0, verbose_name='sort by index'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hottag',
            name='index',
            field=models.IntegerField(default=0, verbose_name='sort by index'),
        ),
        migrations.AlterField(
            model_name='hottag',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='index',
            field=models.IntegerField(default=0, verbose_name='sort by index'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
