# Generated by Django 2.0.3 on 2018-05-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200, verbose_name='publicKey')),
                ('market_hash', models.CharField(max_length=256, verbose_name='market hash')),
                ('content', models.CharField(max_length=200, verbose_name='comment content')),
                ('rating', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='SummaryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash', models.CharField(max_length=256, verbose_name='market hash')),
                ('avg_rating', models.IntegerField(default=1, verbose_name='Average rating')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
    ]
