# Generated by Django 2.0.3 on 2018-05-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarycomment',
            name='sales_number',
            field=models.IntegerField(default=0, verbose_name='Sales number'),
        ),
    ]
