# Generated by Django 2.0.3 on 2018-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletuser',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='avatar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='gender',
            field=models.IntegerField(default=0, verbose_name='0:unknown,1:male,2:female'),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='product_number',
            field=models.IntegerField(null=True),
        ),
    ]
