# Generated by Django 2.0.3 on 2018-05-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180516_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletuser',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
