# Generated by Django 2.0.3 on 2018-05-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_address', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start time')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End time')),
                ('status', models.IntegerField(default=0, verbose_name='0:normal,1:frozen')),
                ('seq', models.IntegerField(verbose_name='Sequence increase')),
                ('file_md5', models.CharField(max_length=32, null=True)),
                ('signature', models.CharField(max_length=200, null=True, verbose_name='Signature created by client')),
                ('msg_hash', models.CharField(max_length=256, null=True, verbose_name='Msg hash(owner_address,title,description,price,created,expired)')),
            ],
        ),
    ]
