# Generated by Django 2.0.3 on 2018-05-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200)),
                ('seller_public_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=40, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_address', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start time')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End time')),
                ('status', models.IntegerField(default=0, verbose_name='0:normal,1:frozen')),
                ('seq', models.IntegerField(verbose_name='Sequence increase')),
                ('file_md5', models.CharField(max_length=32, null=True)),
                ('signature', models.CharField(max_length=200, null=True, verbose_name='Signature created by client')),
                ('msg_hash', models.CharField(max_length=256, null=True, verbose_name='Msg hash(owner_address,title,description,price,created,expired)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.WalletUser')),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash', models.CharField(max_length=256, verbose_name='market hash')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='WalletMsgSequence',
            fields=[
                ('public_key', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='PublicKey')),
                ('seq', models.IntegerField(default=0, verbose_name='seq')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_msg_sequence', to='account.WalletUser', verbose_name='WalletUser')),
            ],
            options={
                'verbose_name': 'WalletUserSequence',
                'verbose_name_plural': 'WalletUserSequences',
            },
        ),
    ]
