# Generated by Django 2.0.3 on 2018-05-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=0, verbose_name='file size'),
        ),
    ]
