# Generated by Django 2.0.3 on 2018-05-03 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0002_product_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletMsgSequence',
            fields=[
                ('public_key', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='PublicKey')),
                ('seq', models.IntegerField(default=0, verbose_name='seq')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_msg_sequence', to='account.WalletUser', verbose_name='WalletUser')),
            ],
            options={
                'verbose_name_plural': 'WalletUserSequences',
                'verbose_name': 'WalletUserSequence',
            },
        ),
    ]
