# Generated by Django 2.0.3 on 2018-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=0, null=True, verbose_name='file size (byte)'),
        ),
    ]
