# Generated by Django 2.1.1 on 2018-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180530_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_md5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='ptype',
            field=models.CharField(choices=[('file', 'file'), ('stream', 'stream')], default='file', max_length=10),
        ),
    ]
