# Generated by Django 2.0.3 on 2018-05-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_walletmsgsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=200, unique=True)),
                ('seller_public_key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyTag',
            fields=[
                ('public_key', models.CharField(max_length=200, unique=True)),
                ('tag', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash', models.CharField(max_length=256, verbose_name='market hash')),
                ('quantity', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
