---

# .mysql_env:
#
# MYSQL_ROOT_PASSWORD=
# MYSQL_DATABASE=
# MYSQL_USER=
# MYSQL_PASSWORD=

version: '2'
services:
  zookeeper:
    image: mysql:5.6
    hostname: pdash
    container_name: market_db
    ports:
      - "3306:3306"
    env_file:
      - ~/.cpchain/.mysql_env
    volumes:
      - ~/.cpchain/pdash_db:/var/lib/mysql
