# Generated by Django 2.0.3 on 2018-05-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSaleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_hash', models.CharField(max_length=256, verbose_name='market hash')),
                ('sales_number', models.IntegerField(default=0, verbose_name='Sales number')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_key', models.CharField(max_length=200, verbose_name='sellerKey')),
                ('market_hash', models.CharField(max_length=256, verbose_name='market hash')),
                ('buyer_key', models.CharField(max_length=200, verbose_name='buyerKey')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
