# Generated by Django 2.0.3 on 2018-05-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='buyer_key',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='seller_key',
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='buyer_address',
            field=models.CharField(max_length=200, null=True, verbose_name='buyer_address'),
        ),
        migrations.AddField(
            model_name='transactiondetail',
            name='seller_address',
            field=models.CharField(max_length=200, null=True, verbose_name='seller_address'),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='market_hash',
            field=models.CharField(max_length=256, null=True, verbose_name='market hash'),
        ),
    ]
